import numpy as np

# what currents are allowed?
CURRENT_LIMITS = sorted([90, 140])
# what currents are preferred?
TARGET_CURRENTS = sorted([90, 140])
MAX_TEMPERATURE = 29
MIN_TEMPERATURE = 20
# the ideal slope of a laser mode
TARGET_SLOPE = -196861482 # Hz / mA
# average frequency span between two adjacent modes
MODE_FREQUENCY_SPACING = 6.1e9 # Hz
CURRENT_MOD_FACTOR = 20  # mA/V

MODE_WIDTH = np.abs(MODE_FREQUENCY_SPACING / TARGET_SLOPE) # mA
MODE_TEMPERATURE_SPACING = 1
COUNTER_MIN_FREQUENCY = 0.5
MAX_MEASURABLE_FREQUENCY = 8e9
RAMP_AMPLITUDE = 0.3
RAMP_FREQUENCY = 10

MEASUREMENT_BASE_RATE = 125e6
REDPITAYA_DATA_POINTS = 16384
DECIMATION_FACTOR = 1024
SCALING = 1.00925
SKIP_POINTS = 100
MEASUREMENT_RATE = MEASUREMENT_BASE_RATE / DECIMATION_FACTOR
MEASUREMENT_TIME = REDPITAYA_DATA_POINTS / MEASUREMENT_RATE
FREQ_MEASUREMENT_RATE = MEASUREMENT_RATE / SCALING / SKIP_POINTS
FREQ_MEASUREMENT_TIME = MEASUREMENT_TIME / SCALING

# which modes should be considered?
DELTA_MODES = [0, 1, -1, 2, -2, 3, -3]
